<div class="cabecera">
	<p>Localizacion de la finca del Productor/a<p>
</div>
<div id="form-01000">
	<table>
		<form name="01000">
			<tr>
				<td><label class="form-font">Departamento: </label></td>
				<td><input type="text" class="form-text" size="15"  name="departamento"></td>
				<td><input type="text" class="form-text" size="4"  name="cod-departamento"></td>
			</tr>
			<tr>
				<td><label class="form-font">Distrito: </label></td>
				<td><input type="text" class="form-text" size="15" name="distrito"></td>
				<td><input type="text" class="form-text" size="4"  name="cod-distrito"></td>
			</tr>
			<tr>
				<td><label class="form-font">Compa&#241;ia: </label></td>
				<td><input type="text" class="form-text" size="15" name="compania"></td>
				<td><input type="text" class="form-text" size="4"  name="cod-compania"></td>
			</tr>
			<tr>
				<td><label class="form-font">Nombre de comite: </label></td>
				<td><input type="text" class="form-text" size="15"  name="comite"></td>
				<td><input type="text" class="form-text" size="4"  name="cod-comite"></td>
			</tr>
			<tr>
				<td><label class="form-font">Colonia/Asentamiento: </label></td>
				<td><input type="text" class="form-text" size="15" name="colonia"></td>
				<td><input type="text" class="form-text" size="4" name="cod-colonia"></td>
			</tr>
			<tr>
				<td><label name="compania" class="form-font">Telefono: </label></td>
				<td><input type="text" class="form-text" size="15"></td>
			</tr>
			<tr>
				<td><label name="compania" class="form-font">Coord. Graficas X: </label></td>
				<td>
					<table>
						<tr>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
							<td><input type="text" class="form-text" size="1"></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td><label name="compania" class="form-font">Coord. Graficas Y: </label></td>
				<td>
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
					<input type="text" class="form-text" size="1">
				</td>
			</tr>
			<tr>
				<td><label name="compania" class="form-font">El productor/a reside en su finca? </label></td>
			</tr>
			<tr>
				<td><input type="radio" name="viveFinca" value="true">Si</td>
					<>
					<input type="text" class="form-text">
				<td><input type="radio" name="viveFinca" value="false">No</td>
			</tr>
			
			
		</form>
	</table>
</div>


<div class="cabecera">
	<p>Identificacion del Productor/a<p>
</div>
<div id="form-02000">
	<form name="02000">
		
	</form>
</div>


<div class="cabecera">
	<p>Composicion familiar y ocupacion<p>
</div>
<div id="form-03000">
	<form name="03000">
		
	</form>
</div>


<div class="cabecera">
	<p>Tenencia de la tierra<p>
</div>
<div id="form-04000">
	<form name="04000">
		
	</form>
</div>


<div class="cabecera">
	<p>Uso de la tierra<p>
</div>
<div id="form-05000">
	<form name="05000">
		
	</form>
</div>


<div class="cabecera">
	<p>Trabajadores contratados<p>
</div>
<div id="form-06000">
	<form name="06000">
		
	</form>
</div>


<div class="cabecera">
	<p>Produccion organica<p>
</div>
<div id="form-07000">
	<form name="07000">
		
	</form>
</div>


<div class="cabecera">
	<p>Cultivos agricolas temporales, permanentes y forestales<p>
</div>
<div id="form-08000">
	<form name="08000">
		
	</form>
</div>


<div class="cabecera">
	<p>Produccion ganadera<p>
</div>
<div id="form-09000">
	<form name="09000">
		
	</form>
</div>


<div class="cabecera">
	<p>Elaboracion de productos de la finca<p>
</div>
<div id="form-10000">
	<form name="10000">
		
	</form>
</div>


<div class="cabecera">
	<p>Implementos e insfraestructura agricola en la finca<p>
</div>
<div id="form-11000">
	<form name="11000">
		
	</form>
</div>


<div class="cabecera">
	<p>Servicios basicos<p>
</div>
<div id="form-12000">
	<form name="12000">
		
	</form>
</div>


<div class="cabecera">
	<p>Cria peces<p>
</div>
<div id="form-13000">
	<form name="13000">
		
	</form>
</div>


<div class="cabecera">
	<p>Utilizacion de insumos<p>
</div>
<div id="form-14000">
	<form name="14000">
		
	</form>
</div>


<div class="cabecera">
	<p>Asistencia tecnica<p>
</div>

<div id="form-15000">
	<form name="15000">
		
	</form>
</div>


<div class="cabecera">
	<p>Asistencia crediticia<p>
</div>

<div id="form-16000">
	<form name="16000">
		
	</form>
</div>


<div class="cabecera">
	<p>Ingresos y egresos de la finca<p>
</div>

<div id="form-17000">
	<form name="17000">
		
	</form>
</div>

<div class="cabecera">
	<p>Incidencia de factores climaticos en los cultivos<p>
</div>
<div id="form-18000">
	<form name="18000">
		
	</form>
</div>

<div class="cabecera">
	<p>Organizacion del productor/a<p>
</div>
<div id="form-19000">
	<form name="19000">
		
	</form>
</div>


<div class="cabecera">
	<p>Informacion agropecuaria<p>
</div>
<div id="form-20000">
	<form name="20000">
		
	</form>
</div>