
<div class="cabecera">
	<p>Localizacion de la finca del Productor/a<p>
</div>
<div id="form-01000">
	<form name="01000">
		<table>
			<tr>
				<td>
					<label for="textDepartamento">Departamento</label>
				</td>
				<td>
					<input type="text" name="textDepartamento" size="20" />
				</td>
				<td>
					<input type="text" name="codDepartamento" size="2" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="textDistrito">Distrito</label>
				</td>
				<td>
					<input type="text" name="textDistrito" size="20" />
				</td>
				<td>
					<input type="text" name="codDistrito" size="2" />
				</td>			
			</tr>
			<tr>
				<td>
					<label for="textConpania">Compa&ntildeia </label>
				</td>
				<td>
					<input type="text" name="textDistrito" size="20" />
				</td>
				<td>
					<input type="text" name="codDistrito" size="2" />
				</td>				
			</tr>
			<tr>
				<td>
					<label for="textComite">Comite</label>
				</td>
				<td>
					<input type="text" name="textDistrito" size="20" />
				</td>
				<td>
					<input type="text" name="codDistrito" size="2" />
				</td>				
			</tr>
			<tr>
				<td>
					<label for="textColonia">Colonia/Asentamiento</label>
				</td>
				<td>
					<input type="text" name="textColonia" size="20" />
				</td>
				<td>
					<input type="text" name="codColonia" size="2" />
				</td>				
			</tr>
			<tr>
				<td>
					<label for="textTelefono" />Telefono</label>
				</td>
				<td>
					<input type="text" name="textTelefono" size="20" />
				</td>
				<td>
					<input type="text" name="codTelefono" size="2" />
				</td>				
			</tr>
			<tr>
				<td>
					<label for="textTelefono" />Coord. Geograficas</label>
				</td>
			</tr>
			<tr>
				<td>
					<label for="coordX">X:</label>
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
				</td>
			</tr>
			<tr>
				<td>
					<label for="coordY">Y:</label>
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
					<input type="text" size="2" class="coordenada">
				</td>
			</tr>
			<tr>
				<td><label for="radioResidencia">El productor/a reside en su finca?</label></td>
			</tr>
			<tr>
				<td><input type="radio" name="radioResidencia" value="true" />Si</td>
			</tr>
			<tr>
				<td><label for="residenciaAnhos">Hace cuantos a&ntildeos?</label></td>
				<td><input type="text" size="2" /></td>
			</tr>
			<tr>
				<td><input type="radio" name="radioResidencia" value="false">No</td>
			</tr>
			<tr>
				<p>Donde reside?</p>
			<tr>
			<tr>
				<td>
					<label for="residenciaTextDistrito">Departamento</label>
				</td>
				<td>
					<input type="text" name="residenciaTextDepartamento" size="20" />
				</td>
				<td>
					<input type="text" name="residenciaCodDepartamento" size="2" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="residenciaTextDistrito">Distrito</label>
				</td>
				<td>
					<input type="text" name="residenciaTextDistrito" size="20" />
				</td>
				<td>
					<input type="text" name="residenciaCodDistrito" size="2" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="residenciaTextCompania">Compa&ntildeia</label>
				</td>
				<td>
					<input type="text" name="residenciaTextCompania" size="20" />
				</td>
				<td>
					<input type="text" name="residenciaCodCompania" size="2" />
			</tr>
			<tr>
				<td>
					<label for="residenciaTextKm">Distancia de la finca (km)</label>
				</td>
				<td>
					<input type="text" name="residenciaCodCompania" size="4" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="selectTipoFInca">Tipo de finca</label>
				</td>
				<td>
				<select name="selectTipoFinca">
				<option name="selectTipoFInca" value="0"/> </option>
				<option name="selectTipoFInca" value="1"/>Agricola</option>
				<option name="selectTipoFInca" value="2"/>Pecuaria</option>
				<option name="selectTipoFInca" value="3"/>Horticola</option>
				<option name="selectTipoFInca" value="4"/>Floricultura</option>
				<option name="selectTipoFInca" value="5"/>Viverista</option>
				<option name="selectTipoFInca" value="6"/>Otros</option>
				</select>
				</td>
			</tr>
		</table>
	</form>
</div>


<div class="cabecera">
	<p>Identificacion del Productor/a<p>
</div>
<div id="form-02000">
	<form name="02000">
		
	</form>
</div>


<div class="cabecera">
	<p>Composicion familiar y ocupacion<p>
</div>
<div id="form-03000">
	<form name="03000">
		
	</form>
</div>


<div class="cabecera">
	<p>Tenencia de la tierra<p>
</div>
<div id="form-04000">
	<form name="04000">
		
	</form>
</div>


<div class="cabecera">
	<p>Uso de la tierra<p>
</div>
<div id="form-05000">
	<form name="05000">
		
	</form>
</div>


<div class="cabecera">
	<p>Trabajadores contratados<p>
</div>
<div id="form-06000">
	<form name="06000">
		
	</form>
</div>


<div class="cabecera">
	<p>Produccion organica<p>
</div>
<div id="form-07000">
	<form name="07000">
		
	</form>
</div>


<div class="cabecera">
	<p>Cultivos agricolas temporales, permanentes y forestales<p>
</div>
<div id="form-08000">
	<form name="08000">
		
	</form>
</div>


<div class="cabecera">
	<p>Produccion ganadera<p>
</div>
<div id="form-09000">
	<form name="09000">
		
	</form>
</div>


<div class="cabecera">
	<p>Elaboracion de productos de la finca<p>
</div>
<div id="form-10000">
	<form name="10000">
		
	</form>
</div>


<div class="cabecera">
	<p>Implementos e insfraestructura agricola en la finca<p>
</div>
<div id="form-11000">
	<form name="11000">
		
	</form>
</div>


<div class="cabecera">
	<p>Servicios basicos<p>
</div>
<div id="form-12000">
	<form name="12000">
		
	</form>
</div>


<div class="cabecera">
	<p>Cria peces<p>
</div>
<div id="form-13000">
	<form name="13000">
		
	</form>
</div>


<div class="cabecera">
	<p>Utilizacion de insumos<p>
</div>
<div id="form-14000">
	<form name="14000">
		
	</form>
</div>


<div class="cabecera">
	<p>Asistencia tecnica<p>
</div>

<div id="form-15000">
	<form name="15000">
		
	</form>
</div>


<div class="cabecera">
	<p>Asistencia crediticia<p>
</div>

<div id="form-16000">
	<form name="16000">
		
	</form>
</div>


<div class="cabecera">
	<p>Ingresos y egresos de la finca<p>
</div>

<div id="form-17000">
	<form name="17000">
		
	</form>
</div>

<div class="cabecera">
	<p>Incidencia de factores climaticos en los cultivos<p>
</div>
<div id="form-18000">
	<form name="18000">
		
	</form>
</div>

<div class="cabecera">
	<p>Organizacion del productor/a<p>
</div>
<div id="form-19000">
	<form name="19000">
		
	</form>
</div>


<div class="cabecera">
	<p>Informacion agropecuaria<p>
</div>
<div id="form-20000">
	<form name="20000">
		
	</form>
</div>