
<head>
    <title>otra pagina</title>

    <link href="<?php echo $this->baseUrl() . '/css/index.css'; ?>" 
          media="all" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/Jquery/index/css/reset.css' ?>" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/Jquery/index/css/supersized.css' ?>" type="text/css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/Jquery/index/css/style.css' ?>" type="text/css">

</head>
<body>
    <header>
        <h1>Ministerio de Agricultura y Ganaderia</h1>
    </header>
   <div id="divisoria"></div>

    <div class="page-container">
        <h1>Ingresar</h1>
        <form action="user/login" method="post">
            <input type="text" name="username" class="username" placeholder="Usuario">
            <input type="password" name="password" class="password" placeholder="Contrase&ntilde;a">
            <button type="submit">Vamos</button>
            <div class="error"><span>+</span></div>
        </form>
    </div>

   <script src="<?php echo $this->baseUrl() . '/Jquery/index/js/jquery-1.10.2.js' ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl() . '/Jquery/index/js/supersized.3.2.7.min.js' ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl() . '/Jquery/index/js/supersized-init.js"' ?>"type="text/javascript" ></script>
    <script src="<?php echo $this->baseUrl() . '/Jquery/index/js/scripts.js' ?>" type="text/javascript"></script>
</body>